In [1]:
#Importing the dependencies
import numpy as np
import pandas as pd

In [2]:
#Loading the given csv files
data1 = pd.read_csv('CSV 1.csv')
data2 = pd.read_csv('CSV 2.csv')
data3 = pd.read_csv('CSV 3.csv')

In [3]:
data1.head() #This dataset contains the details of all the properties.

,id,city,country,fullStreetAddress,postalCode,stateOrProvince,unitNumber,bathrooms,bedrooms,listingDescription,...,yearBuilt,lotSize,lotSizeUnit,propertySubType,listingCategory,numParkingSpaces,createdAt,geocodioAccuracyScore,photoscount,grade
0,2698139,St Peters,US,12 Legacy Estates Lane,63376,MO,NaN,6,5,Tucked away in the private Legacy Estates subd...,...,1998.0,NaN,squareFoot,Single Family Detached,Purchase,3.0,2019-02-21 14:53:27.462+00,NaN,29,awesome
1,2698093,St Louis,US,222 Euclid Avenue,63119,MO,NaN,2,3,This charming Ranch offers hardwood flooring o...,...,1962.0,7753.68,squareFoot,Single Family Detached,Purchase,1.0,2019-02-21 14:53:07.92+00,NaN,29,awesome
2,2698007,Ballwin,US,741 Woodside Trails Drive,63021,MO,NaN,3,3,This is the LARGEST Villa-style condo in this ...,...,1986.0,14766.84,squareFoot,Condominium,Purchase,2.0,2019-02-21 14:52:30.126+00,NaN,29,awesome
3,2697963,Manchester,US,301 Wembley Lane,63021,MO,NaN,2,3,Over 1700 sq ft of updated living space in con...,...,1969.0,11848.32,squareFoot,Single Family Detached,Purchase,2.0,2019-02-21 14:52:11.85+00,NaN,29,awesome
4,2697938,O'fallon,US,27 Clear Meadows,63366,MO,NaN,4,4,"Move in ready, excellent condition. Outstandin...",...,2007.0,10890.00,squareFoot,Single Family Detached,Purchase,3.0,2019-02-21 14:51:55.495+00,NaN,29,awesome

In [4]:
data2.head() #This dataset contains the number of times these properties have been marked as favorite.

        id  favouritecount
0  2698139               0
1  2698093               0
2  2698007               0
3  2697963               0
4  2697938               0

In [5]:
data3.head() #This dataset contains the number of collab projects for these properties.

        id  collabprojectscount
0  2698139                    0
1  2698093                    0
2  2698007                    0
3  2697963                    0
4  2697938                    0

In [6]:
data2['favouritecount'].value_counts() #Dataset 2 contains a column of zeroes.

0    900
Name: favouritecount, dtype: int64

In [7]:
data3['collabprojectscount'].value_counts() #Dataset 3 also contains a column of zeroes.

0    900
Name: collabprojectscount, dtype: int64

## Questions and Answers

**Q1. What kind of classifications would help a real estate platform like Nobbas irrespective of the data that has been provided to you? Categorize these as following:**

**a. Mark a classification “Achievable” if it can be implemented using the provided data.**

**b. Mark it as “Unachievable” if data provided is insufficient.**

Solution 1. The kind of classifications that would help a real estate platform like Nobbas are listed below:

a. Achievable: 
1.	Based on Location: Country/ State or Province/ City/ Street Address/ Postal Code
2.  Based on Listing category: Rental or Purchase
3.	Based on Amenities: Number of Bathrooms/ Bedrooms/ Parking Spaces
4.	Based on Listing title (Residential/ Traditional) and Property subtype (Townhouse/ Condo)  
5.	Based on Price, Lot size, Living area, Year built, Grade and Freshness of the listing	

b. Unachievable:
1.	Based on the number of storeys, number of kitchens, whether the property has a pool or not, type of cooling system (Room air conditioner, Central air conditioner, etc.), type of heating system (Forced air furnaces, hot water boilers, etc.) and type of garage (Attached or detached).

**Q2. Answer the following for a maximum of 3 classifications from the Achievable category:**

**a. Program them and add it to your GitHub repo.**

Solution 2. Following is the code for 3 classifications based on location, whether the property is available for rent or purchase and based on the amenities of these properties.

**For classification based on location of the property**

In [8]:
def location(data, country, state, city='None', street='None', postal_code='none'):
    
    """This function returns the data of properties present in location specified by the user. 
    It takes the data of listings, country and state as mandatory arguments and city, street
    and postal code as optional arguments"""
    
    #Convert the data and the given inputs to lowercase strings for easy comparison
    data = data.apply(lambda x: x.astype(str).str.lower()) #1
    country = country.lower() 
    state = state.lower()
    city = city.lower()
    street = street.lower()
    postal_code = str(postal_code)
    
    #Check the given inputs and return data accordingly.
    if ((city=='none') & (street=='none') & (postal_code=='none')):
        return data[(data['country']==country) & (data['stateOrProvince']==state)]
    
    elif ((city!='none') & (street=='none') & (postal_code=='none')):
        return data[(data['country']==country) & (data['stateOrProvince']==state) & (data['city']==city)]
    
    elif ((city!='none') & (street!='none') & (postal_code=='none')):
        return data[(data['country']==country) & (data['stateOrProvince']==state) & (data['city']==city) &
                    (data['fullStreetAddress']==street)]
    
    elif ((city!='none') & (street=='none') & (postal_code!='none')):
        return data[(data['country']==country) & (data['stateOrProvince']==state) & (data['city']==city) &
                    (data['postalCode']==postal_code)]
    
    elif ((city!='none') & (street!='none') & (postal_code!='none')):
        return data[(data['country']==country) & (data['stateOrProvince']==state) & (data['city']==city) &
                    (data['fullStreetAddress']==street) & (data['postalCode']==postal_code)]

In [9]:
location(data1, country='uS', state='mo', city="O'fallon", postal_code=63366, street='27 clear meadows') #Checking the result of location function.

,id,city,country,fullStreetAddress,postalCode,stateOrProvince,unitNumber,bathrooms,bedrooms,listingDescription,...,yearBuilt,lotSize,lotSizeUnit,propertySubType,listingCategory,numParkingSpaces,createdAt,geocodioAccuracyScore,photoscount,grade
4,2697938,o'fallon,us,27 clear meadows,63366,mo,nan,4,4,"move in ready, excellent condition. outstandin...",...,2007.0,10890.0,squarefoot,single family detached,purchase,3.0,2019-02-21 14:51:55.495+00,nan,29,awesome

**For classification based on the listing category**

In [10]:
def listing_category(data, category):
    
    """This function returns the properties which are either rentals or are available for purchase, based on the given input.
    It takes two mandatory inputs namely: the data of listings and the category specified by the user"""
    
    #Convert the inputs into lowercase and return the instances where the listing category matches the input category.
    category = category.lower()
    return data[data['listingCategory'].apply(lambda x: x.lower())==category]

In [11]:
listing_category(data1, 'rent') #Checking the result of listing_category function.

,id,city,country,fullStreetAddress,postalCode,stateOrProvince,unitNumber,bathrooms,bedrooms,listingDescription,...,yearBuilt,lotSize,lotSizeUnit,propertySubType,listingCategory,numParkingSpaces,createdAt,geocodioAccuracyScore,photoscount,grade
11,2697536,Coral Springs,US,5436 NW 121st Ave,33076,FL,NaN,3,4,Beautiful two story house with 3 Bedrooms + 1 ...,...,2000.0,6969.60,squareFoot,Single Family Detached,Rent,3.0,2019-02-21 14:45:55.769+00,NaN,29,awesome
14,2697464,Miami,US,14300 SW 121st Pl,33186,FL,7,3,3,Location!Location!Location! Bright and beautif...,...,1996.0,NaN,squareFoot,Townhouse,Rent,0.0,2019-02-21 14:45:16.766+00,NaN,29,awesome
17,2697288,Miami Beach,US,753 Michigan Ave,33139,FL,2D,1,1,Rent this cute and super cozy 1bed/1bath unit ...,...,1976.0,NaN,squareFoot,Condominium,Rent,1.0,2019-02-21 14:42:38.12+00,NaN,29,awesome
28,2696520,Miami,US,31 SE 5th,33131,FL,1210,2,2,Brickel attractive lifestyle at 5 star buildi...,...,2006.0,1306.80,squareFoot,Apartment,Rent,1.0,2019-02-21 14:28:18.113+00,NaN,29,awesome
29,2696463,Coconut Grove,US,2831 S BAYSHORE DR,33133,FL,1202,2,2,Park Grove Spectacular 2/2 unit with Oversized...,...,2018.0,NaN,squareFoot,Condominium,Rent,1.0,2019-02-21 14:27:20.709+00,NaN,29,awesome
36,2696160,Miami,US,15065 SW 108 TE,33196,FL,NaN,3,4,BREATH-TAKING TWO STORY HOME WITH VIEW IN A QU...,...,1989.0,NaN,squareFoot,Single Family Detached,Rent,2.0,2019-02-21 14:22:07.332+00,NaN,29,awesome
40,2696021,Aventura,US,3475 N COUNTRY CLUB DR,33180,FL,314,1,1,Wonderful opportunity to live in canalfront bu...,...,1971.0,NaN,squareFoot,Condominium,Rent,1.0,2019-02-21 14:20:00.88+00,NaN,29,awesome
41,2695964,Bay Harbor Islands,US,10350 W BAY HARBOR DR,33154,FL,8L,1,1,Completely remodeled just finished never lived...,...,1966.0,NaN,squareFoot,Condominium,Rent,1.0,2019-02-21 14:19:17.009+00,NaN,29,awesome
42,2695913,Miramar,US,3822 SW 171st Ave,33027,FL,NaN,3,4,Beautiful 4 Bedrooms 2.5 Bathrooms with attach...,...,2002.0,4791.60,squareFoot,Townhouse,Rent,1.0,2019-02-21 14:17:47.49+00,NaN,29,awesome
45,2683453,Las Vegas,US,4430 PEACEFUL HARBOR Street,89129,NV,NaN,3,3,REMARKABLE 2-STORY HOME IN GATED COMMUNITY BOA...,...,2004.0,4791.60,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:47.234+00,NaN,35,awesome
46,2683452,Las Vegas,US,6640 ABRUZZI Drive,89084,NV,203,2,3,"Immaculate 2nd floor unit with high ceilings,s...",...,2006.0,NaN,squareFoot,Condominium,Rent,NaN,2019-02-21 12:12:47.198+00,NaN,50,awesome
47,2683451,Las Vegas,US,3473 VILLA KNOLLS SOUTH Drive,89120,NV,NaN,2,3,B-E-AUTIFUL Townhouse w/3 spacious Bedrooms 1 ...,...,1972.0,871.20,squareFoot,Townhouse,Rent,NaN,2019-02-21 12:12:47.153+00,NaN,40,awesome
48,2683450,Las Vegas,US,555 SILVERADO RANCH Boulevard,89123,NV,1009,2,2,B-E-AUTIFUL 2 bedroom 1st floor unit! This hom...,...,1999.0,NaN,squareFoot,Condominium,Rent,NaN,2019-02-21 12:12:47.046+00,NaN,47,awesome
49,2683449,North Las Vegas,US,5912 FOREST CREEK Road,89031,NV,0,3,4,Great 4 Bedroom spacious home over 2000 sq ft....,...,2000.0,6098.40,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:47.043+00,NaN,35,awesome
50,2683448,Las Vegas,US,9050 TROPICANA Avenue,89147,NV,1171,4,3,~TRULY IMPECCABLE UPGRADED PARTIALLY FURNISHED...,...,2007.0,NaN,squareFoot,Condominium,Rent,NaN,2019-02-21 12:12:46.824+00,NaN,48,awesome
53,2683440,Las Vegas,US,3111 BEL AIR Drive,89109,NV,6A,3,2,STUNNING FULLY FURNISHED HIGH-RISE CONDO ON TH...,...,1974.0,NaN,squareFoot,Condominium,Rent,NaN,2019-02-21 12:12:43.599+00,NaN,47,awesome
54,2683435,Las Vegas,US,3111 BEL AIR Drive,89109,NV,23E,2,1,BEAUTIFUL TOTALLY REMODELED CONDO ON THE 23RD ...,...,1974.0,NaN,squareFoot,Condominium,Rent,NaN,2019-02-21 12:12:42.724+00,NaN,34,awesome
55,2683432,Henderson,US,3133 GIVERNY BRIDGE Avenue,89044,NV,NaN,3,3,Stunning former model home with custom 2 tone ...,...,2007.0,3920.40,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:41.881+00,NaN,40,awesome
64,2683415,Las Vegas,US,8241 RUBY MOUNTAIN Way,89128,NV,NaN,3,5,Beautiful 5 bedroom home in The Pueblo near Su...,...,1995.0,5227.20,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:35.82+00,NaN,33,awesome
66,2683406,Las Vegas,US,1417 CANYON LEDGE Court,89117,NV,NaN,4,3,Beautiful Blue Heron Design Executive Loft Sty...,...,2007.0,6534.00,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:32.454+00,NaN,50,awesome
76,2683392,Other,US,5926 SILVER TRACE Court,89011,NV,NaN,3,4,"*** BEAUTIFUL 2 STORY HOME, 4 BEDROOM, 2.5 BAT...",...,2003.0,4791.60,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:22.94+00,NaN,47,awesome
77,2683391,Las Vegas,US,516 WATKINS Drive,89107,NV,NaN,2,4,***BEAUTIFUL FURNISHED SINGLE STORY HOME ON LA...,...,1976.0,9583.20,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:22.852+00,NaN,33,awesome
79,2683388,Las Vegas,US,7007 WESTPARK Court,89147,NV,NaN,2,4,Furnished single story centrally located; move...,...,1972.0,6098.40,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:22.37+00,NaN,32,awesome
80,2683386,Las Vegas,US,10509 JEREMY POINTE Avenue,89144,NV,NaN,2,3,Stunning 3 bedroom 2 bath single story home in...,...,1999.0,4356.00,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:21.568+00,NaN,35,awesome
86,2683366,Henderson,US,362 GRACIOUS Way,89011,NV,NaN,4,4,"READY FOR MOVE IN ~ 3 beds, 3.5 baths, 2 car g...",...,2017.0,3049.20,squareFoot,Single Family Detached,Rent,NaN,2019-02-21 12:12:09.699+00,NaN,47,awesome
92,2651253,Lucas,US,710 Inverness Lane,75002,TX,NaN,3,4,"LOVEJOY SCHOOLS!!! NEW, one story custom home ...",...,2018.0,43734.24,squareFoot,Single Family Detached,Rent,3.0,2019-02-10 10:02:53.388+00,1.0,33,awesome
93,2651251,Prosper,US,1821 Shavano Way,75078,TX,NaN,3,4,This luxury community offers oversized home si...,...,2017.0,15028.20,squareFoot,Single Family Detached,Rent,3.0,2019-02-10 10:02:53.297+00,1.0,31,awesome
94,2651249,Prosper,US,621 Sunbury Lane,75078,TX,NaN,3,4,This community offers oversized home sites wit...,...,2018.0,15246.00,squareFoot,Single Family Detached,Rent,3.0,2019-02-10 10:02:53.242+00,1.0,30,awesome
95,2651248,Lucas,US,720 Inverness Lane,75002,TX,NaN,4,4,"LOVEJOY SCHOOLS!!! NEW, one story custom home ...",...,2017.0,47001.24,squareFoot,Single Family Detached,Rent,3.0,2019-02-10 10:02:52.937+00,1.0,30,awesome
96,2651247,Lucas,US,730 Inverness Lane,75002,TX,NaN,4,4,"LOVEJOY SCHOOLS!!! NEW, one story custom home ...",...,2017.0,53056.08,squareFoot,Single Family Detached,Rent,3.0,2019-02-10 10:02:52.875+00,1.0,33,awesome
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,1328672,Denton,US,4704 Beaver Creek Avenue,76207,TX,NaN,3,4,Applicants 18 and older must apply and pay app...,...,2018.0,5706.36,squareFoot,Single Family Detached,Rent,2.0,2018-10-11 19:33:19.254+00,NaN,20,good
456,1328226,Rowlett,US,4501 Brittany Drive,75088,TX,NaN,3,3,Beautiful 2 story home with a backyard that is...,...,2000.0,10541.52,squareFoot,Single Family Detached,Rent,2.0,2018-10-11 19:32:02.307+00,NaN,21,good
460,1317863,JACKSONVILLE,US,3218 HERSCHEL ST,32205,FL,1,1,1,1/1 APARTMENT conveniently located in Avondal...,...,1942.0,NaN,squareFoot,Quadruplex,Rent,1.0,2018-10-11 18:48:01.692+00,NaN,7,good
476,1305005,SKOKIE,US,4828 Jarvis Avenue,60077,IL,NaN,2,3,Spacious 4 level home in desirable Fairview sc...,...,1956.0,NaN,squareFoot,Single Family Detached,Rent,1.0,2018-10-11 17:56:34.143+00,NaN,28,awesome
478,1304438,Red Bank,US,43 Lexington Court,7701,NJ,NaN,1,1,"Middletown Township but actual zip code, 07701...",...,1976.0,NaN,squareFoot,Other,Rent,0.0,2018-10-11 17:53:52.23+00,NaN,28,awesome
491,1279603,Virginia Beach,US,1241 Northvale DR,23464,VA,NaN,13,4,GREAT FAMILY HOME AVAILABLE; 4 BEDROOMS 2 AND ...,...,1986.0,NaN,squareFoot,Single Family Detached,Rent,NaN,2018-10-11 16:35:47.473+00,NaN,28,awesome
494,1262477,Spring Hill,US,8387 Eric Street,34606,FL,NaN,1,2,GREAT 2 BEDROOM HOME WITH RECENTLY UPGRADED IN...,...,1980.0,17424.00,squareFoot,Other,Rent,2.0,2018-10-11 15:43:29.058+00,NaN,9,good
517,1143517,Jamaica,US,116th Ave,11412,NY,NaN,0,0,"Cozy and neat apartment, stainless appliances,...",...,NaN,NaN,squareFoot,Apartment,Rent,0.0,2018-09-20 07:37:31.405+00,NaN,0,bad
520,1131084,River Edge,US,37 Jordan Drive,7661,NJ,NaN,3,3,"FABULOUS END UNIT 3BR, 2.5 BTH TOWNHOUSE FACIN...",...,1990.0,NaN,squareFoot,Townhouse,Rent,1.0,2018-09-20 06:51:24.779+00,NaN,0,bad
528,1116734,Aiken,US,1636 Hampton Ave NW,29801,SC,NaN,0,0,"Office building consisting of approximately 7,...",...,NaN,28314.00,squareFoot,Other,Rent,NaN,2018-09-20 06:04:24.661+00,NaN,1,bad
538,1097530,Miami Beach,US,1130 11th St #5B,33139,FL,NaN,2,1,Gorgeous modern furnished 1 bedroom 1 and 1/2 ...,...,1968.0,NaN,squareFoot,Condominium,Rent,1.0,2018-09-17 06:40:37.731+00,NaN,18,good
545,1088733,Maricopa,US,45416 W APPLEGATE Road,85139,AZ,NaN,2,4,ALL NEW CUSTOM 2 TONE PAINT & NEW CARPET INSTA...,...,2006.0,NaN,squareFoot,Single Family Detached,Rent,NaN,2018-09-17 06:05:59.13+00,NaN,9,good
549,1076859,Virginia Beach,US,1680 Castlefield Road,23456,VA,NaN,3,4,Excellent 4 bedroom home in the heart of Virgi...,...,1987.0,NaN,squareFoot,Single Family Detached,Rent,NaN,2018-09-14 08:10:16.201+00,NaN,26,good
557,1066127,Colleyville,US,5101 Oak Timbers Court,76034,TX,NaN,6,4,"Elegant, charming, open floor plan home locate...",...,2004.0,33976.80,squareFoot,Single Family Detached,Rent,3.0,2018-09-14 07:50:51.037+00,NaN,0,bad
566,1023817,Atlantic City,US,108 S Montpelier Avenue,8401,NJ,NaN,1,0,Oceanfront Unit - Close proximity to Stockton ...,...,NaN,NaN,squareFoot,Other,Rent,NaN,2018-09-10 07:39:47.75+00,NaN,1,bad
591,983301,Plant City,US,1400 STRAWBERRY PLACE,33563,FL,18,1,1,Available Now!!!\n\nWelcome to Casa De Strawbe...,...,1982.0,165528.00,squareFoot,Apartment,Rent,NaN,2018-09-07 18:18:53.886+00,NaN,1,bad
593,982185,farrockaway,US,2919 seagirt,11691,NY,NaN,0,3,tenant pays broker fee and all utillities,...,NaN,NaN,squareFoot,Other,Rent,0.0,2018-09-07 18:14:36.67+00,NaN,0,bad
603,972861,LAKE MARY,US,4904 SAN MARINO CIRCLE,32746,FL,NaN,4,4,"Gorgeous 4 bdrm, 3 1/2 bath 3 story townhouse ...",...,2006.0,1306.80,squareFoot,Townhouse,Rent,2.0,2018-09-07 17:46:20.499+00,NaN,28,good
609,969161,BRAMPTON,CA,5 EVANWOOD CRES N,L6X0P8,ON,NaN,4,4,"Semi Detach With 4 Bedrooms , 3 Full Washrooms...",...,NaN,NaN,squareFoot,Single Family Attached,Rent,NaN,2018-09-07 17:32:44.327+00,NaN,1,bad
629,960838,Dothan,US,208 Nypro Lane,36305,AL,NaN,0,0,fully heated/cooled facility rent is $1...,...,NaN,NaN,squareFoot,Other,Rent,NaN,2018-09-07 17:09:39.859+00,NaN,1,bad
775,273566,Atlanta,US,1080 Peachtree St,30309-6831,GA,911,3,2,"DESIRABLE SW CORNER, 11 STACK FOR RENT IN MIDT...",...,2008.0,NaN,squareFoot,Single Family Attached,Rent,NaN,2018-09-05 20:43:52.888+00,NaN,0,bad
776,273166,Jonesboro,US,562 Country Greens,30238,GA,NaN,3,3,NICE 3 BEDROOM 2.5 BATH TOWN HOME IN JONESBORO...,...,1974.0,NaN,squareFoot,Single Family Attached,Rent,NaN,2018-09-05 20:43:47.483+00,NaN,14,good
778,259270,Carroll,US,206 W 5th Street,51401,IA,NaN,0,0,NaN,...,1971.0,NaN,squareFoot,Other,Rent,NaN,2018-09-05 20:39:49.647+00,NaN,0,bad
779,253506,LEHIGH ACRES,US,602 Joel BLVD,33936,FL,NaN,1,1,"Charming 1 Bedroom, 1 Bathroom available for r...",...,1971.0,NaN,squareFoot,Single Family Attached,Rent,NaN,2018-09-05 20:38:35.568+00,NaN,10,good
781,249121,Duluth,US,140 Jilstone Court,30097,GA,NaN,4,5,"YOU'LL LOVE THIS BEAUTIFUL, IMPRESSIVE HOME. S...",...,2003.0,NaN,squareFoot,Single Family Detached,Rent,NaN,2018-09-05 20:37:24.555+00,NaN,36,good
782,243028,Marietta,US,1674 Grist Mill Drive,30062,GA,NaN,3,2,Recently updated hilltop townhouse in East Cob...,...,1986.0,NaN,squareFoot,Townhouse,Rent,NaN,2018-09-05 20:36:02.174+00,NaN,11,good
816,150396,Los Angeles (City),US,350 FORDYCE Road,90049,CA,NaN,6,5,Gated Contemporary home located in Brentwood C...,...,1986.0,15992.00,squareFoot,Single Family Detached,Rent,0.0,2018-09-05 20:12:34.353+00,NaN,20,good
827,119734,Columbia,US,3223 DOVE DR,65202,MO,NaN,2,3,"Spacious unit with open design, large kitchen,...",...,2003.0,NaN,squareFoot,Duplex,Rent,NaN,2018-09-05 20:04:40.861+00,NaN,0,bad
851,45418,Philadelphia,US,1324 Locust,19107,PA,NaN,1,0,"Rent includes heat, water, AC, cable, trash, g...",...,NaN,18992160.00,squareFoot,Single Family Detached,Rent,0.0,2018-09-05 19:45:32.019+00,NaN,0,bad
858,42221,Aventura,US,20301 W COUNTRY CLUB DR,33180,FL,1430,2,2,"COMPLETELY REMODELED!!! spectacular unit, GOLF...",...,1975.0,NaN,squareFoot,Condominium,Rent,1.0,2018-08-25 06:04:45.84+00,NaN,31,good

**For classification based on amenities**

In [12]:
def amenities(data, bathrooms='none', bedrooms='none', parking='none'):
    
    """This function returns the data of properties, which have amenities matching those specified by the user.
    It takes the data of listings as mandatory input. Atleast one argument out of the number of bathrooms, 
    bedrooms and parking spaces is required."""
    
    #Check the given inputs and return data accordingly
    if ((bathrooms!='none') & (bedrooms!='none') & (parking!='none')):
        return data[(data['bathrooms']==bathrooms) & (data['bedrooms']==bedrooms) & (data['numParkingSpaces']==parking)]
    
    elif ((bathrooms!='none') & (bedrooms=='none') & (parking=='none')):
        return data[data['bathrooms']==bathrooms]
    
    elif ((bathrooms=='none') & (bedrooms!='none') & (parking=='none')):
        return data[data['bedrooms']==bedrooms]
    
    elif ((bathrooms=='none') & (bedrooms=='none') & (parking!='none')):
        return data[data['numParkingSpaces']==parking]
    
    elif ((bathrooms!='none') & (bedrooms!='none') & (parking=='none')):
        return data[(data['bathrooms']==bathrooms) & (data['bedrooms']==bedrooms)]
    
    elif ((bathrooms!='none') & (bedrooms=='none') & (parking!='none')):
        return data[(data['bathrooms']==bathrooms) & (data['numParkingSpaces']==parking)]
    
    elif ((bathrooms=='none') & (bedrooms!='none') & (parking!='none')):
        return data[(data['bedrooms']==bedrooms) & (data['numParkingSpaces']==parking)]

In [13]:
amenities(data1, bathrooms=3, bedrooms=4, parking=2) #Checking the result of amenities function.

,id,city,country,fullStreetAddress,postalCode,stateOrProvince,unitNumber,bathrooms,bedrooms,listingDescription,...,yearBuilt,lotSize,lotSizeUnit,propertySubType,listingCategory,numParkingSpaces,createdAt,geocodioAccuracyScore,photoscount,grade
5,2697936,Wildwood,US,16779 Hickory Crest Drive,63011,MO,NaN,3,4,Beautiful Hickory Manor home just hit the mark...,...,1999.0,6098.40,squareFoot,Single Family Detached,Purchase,2.0,2019-02-21 14:51:54.803+00,NaN,29,awesome
26,2696607,Miami Gardens,US,3290 NW 169th Ter,33056,FL,NaN,3,4,Beautiful all new remodeled 4/2.5 home. Brand ...,...,1955.0,8276.40,squareFoot,Single Family Detached,Purchase,2.0,2019-02-21 14:29:44.764+00,NaN,29,awesome
30,2696369,Homestead,US,2214 NE 41st Ave,33033,FL,NaN,3,4,"Beautifully maintained 4 Bedroom, 2 Bathroom H...",...,2003.0,4791.60,squareFoot,Single Family Detached,Purchase,2.0,2019-02-21 14:25:17.776+00,NaN,29,awesome
36,2696160,Miami,US,15065 SW 108 TE,33196,FL,NaN,3,4,BREATH-TAKING TWO STORY HOME WITH VIEW IN A QU...,...,1989.0,NaN,squareFoot,Single Family Detached,Rent,2.0,2019-02-21 14:22:07.332+00,NaN,29,awesome
100,2651210,Allen,US,1078 James Court,75013,TX,NaN,3,4,"FOR LEASE, New Construction Home in Twin Creek...",...,2019.0,5880.60,squareFoot,Single Family Detached,Rent,2.0,2019-02-10 10:02:03.789+00,1.0,35,awesome
124,2466710,Huntersville,US,15414 Stillwater Crossing Lane,28078-4680,NC,NaN,3,4,"Come see this highly sought after, all one lev...",...,2008.0,11761.20,squareFoot,Single Family Detached,Purchase,2.0,2019-01-26 08:00:57.086+00,NaN,31,awesome
175,2210925,Mt Washington,US,192 Scenic View Dr,40047,KY,NaN,3,4,This lovely brick and vinyl home is perfect fo...,...,2001.0,20908.80,squareFoot,Single Family Detached,Purchase,2.0,2019-01-03 08:29:02.711+00,NaN,29,awesome
265,1948502,Baxter,US,5615 Rush Lake Court,56425,MN,NaN,3,4,"Rare find! Rush Lake townhome 4 bedrooms, 3 ba...",...,2004.0,3484.80,squareFoot,Townhouse,Purchase,2.0,2018-12-01 08:15:39.63+00,NaN,34,awesome
279,1910044,Louisville,US,846 Lake Forest Pkwy,40245,KY,NaN,3,4,Over 3000 square feet of living space on the f...,...,1991.0,11761.20,squareFoot,Single Family Detached,Purchase,2.0,2018-11-29 08:39:53.519+00,NaN,61,awesome
286,1906606,Wildwood Crest,US,6210 Ocean,8260,NJ,207,3,4,Back on the market and ready to sell!!! This ...,...,2010.0,NaN,squareFoot,Condominium,Purchase,2.0,2018-11-29 07:44:17.975+00,NaN,23,good
341,1716382,Sherwood,US,7360 West Ridge Circle,72120,AR,NaN,3,4,"Beautiful 4 BR, freshly updated home with plen...",...,2002.0,10018.80,squareFoot,Single Family Detached,Purchase,2.0,2018-11-09 07:20:31.186+00,NaN,36,good
384,1568418,Los Alamitos,US,3632 Fenley Drive,90720,CA,NaN,3,4,EARLY PREVIEW! We are proud to present this 2 ...,...,1969.0,5920.00,squareFoot,Single Family Detached,Purchase,2.0,2018-10-30 11:30:36.202+00,NaN,67,good
433,1379810,Greensboro,US,3213 Cheswick Drive,27410,NC,NaN,3,4,Fantastic Updated 4 bedroom home in popular Ed...,...,1997.0,9147.60,squareFoot,Single Family Detached,Purchase,2.0,2018-10-11 23:04:45.274+00,NaN,30,awesome
434,1379418,Kernersville,US,1505 Ballard Court,27284,NC,NaN,3,4,Beautiful 2 Story Home with 4 Bedrooms and 2.5...,...,1999.0,17859.60,squareFoot,Single Family Detached,Purchase,2.0,2018-10-11 23:02:39.263+00,NaN,30,awesome
455,1328672,Denton,US,4704 Beaver Creek Avenue,76207,TX,NaN,3,4,Applicants 18 and older must apply and pay app...,...,2018.0,5706.36,squareFoot,Single Family Detached,Rent,2.0,2018-10-11 19:33:19.254+00,NaN,20,good
471,1307848,NAPERVILLE,US,1317 Cortland Drive,60565,IL,NaN,3,4,UNBEATABLE LOCATION/204 SCHOOLS/4 LARGE BEDROO...,...,1988.0,7683.98,squareFoot,Single Family Detached,Purchase,2.0,2018-10-11 18:06:05.548+00,NaN,31,awesome
487,1290412,DADE CITY,US,36139 MARKREE CASTLE AVENUE,33525,FL,NaN,3,4,Don't let the opportunity to own a newer style...,...,2009.0,6969.60,squareFoot,Single Family Detached,Purchase,2.0,2018-10-11 17:10:09.868+00,NaN,28,awesome
499,1230809,Charlotte,US,10410 Paisley Abbey Lane,28273-0300,NC,NaN,3,4,"Built in 2016, this Charlotte two-story offers...",...,2016.0,8145.72,squareFoot,Single Family Detached,Purchase,2.0,2018-10-11 14:06:16.69+00,NaN,25,good
513,1163202,Goose Creek,US,101 Monsarret Lane,29445,SC,NaN,3,4,Sellers are Motivated to sell!!!Lots of upgrad...,...,1993.0,NaN,squareFoot,Single Family Detached,Purchase,2.0,2018-09-25 06:27:15.667+00,NaN,0,bad
536,1099407,Bethlehem,US,3722 Ironstone Road,18020,PA,NaN,3,4,NEW CONSTRUCTION!! Very seldom will you find a...,...,1968.0,18513.00,squareFoot,Single Family Detached,Purchase,2.0,2018-09-17 06:47:17.201+00,NaN,24,good
539,1097339,Cromwell,US,1950 N Wood Way,46732,IN,NaN,3,4,Wonderful large country home located in Woodvi...,...,1999.0,151588.80,squareFoot,Single Family Detached,Purchase,2.0,2018-09-17 06:39:17.448+00,NaN,24,good
564,1031635,Cheyenne,US,5515 ALEX RANCH RD,82007,WY,NaN,3,4,Great investment property. Currently has tenan...,...,2014.0,4791.60,squareFoot,Single Family Attached,Purchase,2.0,2018-09-14 06:16:24.567+00,NaN,0,bad
587,991203,Greensboro,US,15 Finley Ridge Way,27455,NC,NaN,3,4,The Linville B Interior: 2439 sq. ft. 4 beds ...,...,2018.0,1742.40,squareFoot,Townhouse,Purchase,2.0,2018-09-07 18:37:57.911+00,NaN,1,bad
648,765840,Chapel Hill,US,1703 Evelyn Ave,37034,TN,NaN,3,4,New Construction. Taxes are estimated. Square ...,...,2018.0,218235.60,squareFoot,Single Family Detached,Purchase,2.0,2018-09-05 22:49:46.21+00,NaN,0,bad
724,458894,North Brunswick,US,1441 Masoma Road,8902,NJ,NaN,3,4,Spacious and clean 4 BD 3 BTH Colonial with fi...,...,1987.0,8485.49,squareFoot,Single Family Detached,Purchase,2.0,2018-09-05 21:33:06.736+00,NaN,25,good
737,411351,Santa Teresa,US,917 Bronze Hill Avenue,88008,NM,NaN,3,4,The Parasio with 4 bedrooms and 3 baths. Home...,...,2018.0,5662.80,squareFoot,Single Family Detached,Purchase,2.0,2018-09-05 21:17:46.632+00,NaN,0,bad
786,221791,Sanford,US,40 E Landing,27332,NC,NaN,3,4,-WATER FRONT home with a dream view of rare be...,...,1977.0,NaN,squareFoot,Single Family Detached,Purchase,2.0,2018-09-05 20:30:34.08+00,NaN,0,bad
855,44656,St. Andrew West,CA,17249 Wheeler Road,K0C 2A0,ON,NaN,3,4,"Beautiful country property, ideal for commuter...",...,1988.0,NaN,squareFoot,Single Family Detached,Purchase,2.0,2018-09-05 19:45:22.748+00,NaN,0,bad
881,11313,Davie,US,4000 SW 109th Ave,33328,FL,NaN,3,4,LOCATION! LOCATION! THE ONE STORY HOME WITH SW...,...,1974.0,43560.00,squareFoot,Single Family Detached,Purchase,2.0,2018-07-03 03:04:50.729+00,NaN,38,good

**Q3. Answer the following for a maximum of 3 classifications from the Unachievable category:**

**a. What data would you need to achieve the classification?**

**b. How would you implement it if you get the data?**

Solution 3 a. To achieve the classification, I would need some more details about the properties, namely: The number of storeys, number of kitchens, whether the property has a pool or not, type of cooling and heating system and type of garage.

Solution 3 b. To implement the classification, I would compare the inputs given by user to the respective elements present in the record. Then those instances, for which the elements of the record match the given inputs, will be returned. This process would be similar to the process implemented in solution 2.

## Reference Links:

**For Solution 1 b:**

Type of Heating systems: https://www.energydepot.com/RPUres/library/homeheating.asp

Type of Cooling systems: https://www.energy.gov/energysaver/home-cooling-systems/air-conditioning

**For Solution 2**

#1 Mike Woodcock's answer to: https://stackoverflow.com/questions/22245171/how-to-lowercase-a-python-dataframe-string-column-if-it-has-missing-values